#!/bin/sh

set -eu

if [ ${#} -lt 2 ]; then
  echo "Usage: ${0} <branch name> <description for when the branch is finished and merged>"
  exit 1
fi

./pull > /dev/null 2>&1 || ./pull
git checkout -b ${1} > /dev/null 2>&1 || git checkout -b ${1}
./quick-push "${*:2}" > /dev/null 2>&1 || ./quick-push "${*:2}"
echo "Branch \`${1}\` created and pushed to origin"
