#!/bin/sh

set -eu

if [ ${#} -ne 1 ]; then
  echo "Usage: ${0} <branch name>"
  exit 1
fi

./pull > /dev/null 2>&1 || ./pull
git checkout -b ${1} > /dev/null 2>&1 || git checkout -b ${1}
git push -u origin ${1} > /dev/null 2>&1 || git push -u origin ${1}
echo "Branch \`${1}\` created and pushed to origin"
