#!/bin/sh

set -eu

if [ ${#} -lt 1 ]; then
  echo "Usage: ${0} <branch name> <description for when the branch is finished and merged>"
  exit 1
fi

git checkout -b ${1} > /dev/null 2>&1 || git checkout -b ${1}
./push "${*:2}" > /dev/null 2>&1 || ./push "${*:2}"
echo "${1} created and pushed to origin"
