#!/bin/sh

set -eu

git checkout main > /dev/null 2>&1 || git checkout main
git pull > /dev/null 2>&1 || git pull
git remote prune origin > /dev/null 2>&1 || git remote prune origin
echo 'Up to date!'
